# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Maven Test

on:
  # allow direct trigger
  workflow_dispatch:
  push:
    paths:
      - '**/workflows/maventest.yml'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        # Look for older version of crypto library
        os: [macos-10.14, ubuntu-latest, windows-latest]
        java: [ 8 ]
        experimental: [false]
      fail-fast: false
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: OpenSSL version
      run: openssl version
    - name: Build with Maven
      # OPENSSL_HOME is needed for Windows build; not used by other builds so can set unconditionally
      # It's not clear how one is supposed to find the correct setting;
      # The value below was found by searching for openssl files under C (warning: slow)
      # Other possible values are:
      # "C:\\Miniconda\\pkgs\\openssl-1.1.1n-h2bbff1b_0\\Library"
      # "C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\opt"
      env:
        OPENSSL_HOME: "C:\\Miniconda\\Library"
      run: |
        mvn -Drat.skip -Danimal.snuffer.skip --no-transfer-progress test-compile
        mvn -q exec:java -D"exec.mainClass=org.apache.commons.crypto.Crypto"
        mvn -q exec:java -D"exec.mainClass=org.apache.commons.crypto.jna.OpenSslJna"
